name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake eating SWAYAM
        uses: Platane/snk@v3
        with:
          github_user_name: nyctzo
          text: "SWAYAM"
          snake_color: "#39ff14"
          text_color: "#39ff14"
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark

      - name: Commit and push snake animation
        uses: EndBug/add-and-commit@v9
        with:
          add: "output"
          message: "Update snake animation"
          default_author: github_actions

          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


